# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0356a3dbb0d34c1af9417d090a95cef46374663e530f43a20a88d2959932ade590788961309f8feb6a32e4b6e9bdd3156ec62594b0622983f028f83dc79745f9

test:
  secret_key_base: 8ccc25cdc69ad6761d79045b2cfacecae417b0d4802067023704a6fc18ddb6498b9a8bc69aaecbe49a79f3d057c002d6f52147c4bcb3b40ca15167f5631746fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
